#!/usr/bin/env python3
"""generate_use_cases.py - 生成使用场景Mock数据

功能：
- 为每个商业软件生成3个使用场景（professional/educational/personal）
- 每个场景20种语言的描述
- 总数据量：500软件 × 3场景 × 20语言 = 30,000条
- 输出到 data/use_cases/{software_id}-{scenario}-{lang}.json

用法：
  python3 -m pipeline.generate_use_cases
  python3 -m pipeline.generate_use_cases --data-dir data
"""
import argparse
import json
import sys
import time
from concurrent.futures import ThreadPoolExecutor, as_completed
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List

from tqdm import tqdm

SCHEMA_VERSION = "1.0.0"

# 20种目标语言（不含 en 源语言）
LANGUAGES = [
    "zh", "ja", "ko", "es",
    "de", "fr", "pt", "it", "ru", "ar",
    "nl", "pl", "tr", "id", "vi", "th",
    "hi", "bn", "ms", "uk",
]

# 3种使用场景
SCENARIOS = ["professional", "educational", "personal"]

# 多语言模板（title/desc 中支持 {name} 和 {activity} 占位符）
LANGUAGE_TEMPLATES = {
    "zh": {
        "professional_title": "{name} 专业使用场景",
        "professional_desc": "在专业工作中使用 {name} 进行{activity}。",
        "educational_title": "{name} 教育使用场景",
        "educational_desc": "在教学场景中使用 {name} 进行{activity}。",
        "personal_title": "{name} 个人使用场景",
        "personal_desc": "在个人生活中使用 {name} 进行{activity}。",
    },
    "ja": {
        "professional_title": "{name} プロフェッショナル使用例",
        "professional_desc": "プロの現場で {name} を使って{activity}を行います。",
        "educational_title": "{name} 教育使用例",
        "educational_desc": "教育現場で {name} を使って{activity}を行います。",
        "personal_title": "{name} 個人使用例",
        "personal_desc": "個人の生活で {name} を使って{activity}を行います。",
    },
    "ko": {
        "professional_title": "{name} 전문 사용 사례",
        "professional_desc": "전문 작업에서 {name}을(를) 사용하여 {activity} 수행합니다.",
        "educational_title": "{name} 교육 사용 사례",
        "educational_desc": "교육 현장에서 {name}을(를) 사용하여 {activity} 수행합니다.",
        "personal_title": "{name} 개인 사용 사례",
        "personal_desc": "개인 생활에서 {name}을(를) 사용하여 {activity} 수행합니다.",
    },
    "es": {
        "professional_title": "Casos de uso profesional de {name}",
        "professional_desc": "Usa {name} en el trabajo profesional para {activity}.",
        "educational_title": "Casos de uso educativo de {name}",
        "educational_desc": "Usa {name} en entornos educativos para {activity}.",
        "personal_title": "Casos de uso personal de {name}",
        "personal_desc": "Usa {name} en la vida personal para {activity}.",
    },
    "de": {
        "professional_title": "Professionelle Anwendungsfälle für {name}",
        "professional_desc": "Verwende {name} bei der professionellen Arbeit für {activity}.",
        "educational_title": "Bildungsszenarien für {name}",
        "educational_desc": "Verwende {name} in Bildungsszenarien für {activity}.",
        "personal_title": "Persönliche Anwendungsfälle für {name}",
        "personal_desc": "Verwende {name} im persönlichen Alltag für {activity}.",
    },
    "fr": {
        "professional_title": "Cas d'usage professionnel de {name}",
        "professional_desc": "Utilisez {name} dans un cadre professionnel pour {activity}.",
        "educational_title": "Cas d'usage éducatif de {name}",
        "educational_desc": "Utilisez {name} dans un cadre éducatif pour {activity}.",
        "personal_title": "Cas d'usage personnel de {name}",
        "personal_desc": "Utilisez {name} dans la vie personnelle pour {activity}.",
    },
    "pt": {
        "professional_title": "Casos de uso profissional do {name}",
        "professional_desc": "Use o {name} no trabalho profissional para {activity}.",
        "educational_title": "Casos de uso educacional do {name}",
        "educational_desc": "Use o {name} em ambientes educacionais para {activity}.",
        "personal_title": "Casos de uso pessoal do {name}",
        "personal_desc": "Use o {name} na vida pessoal para {activity}.",
    },
    "it": {
        "professional_title": "Casi d'uso professionali di {name}",
        "professional_desc": "Usa {name} nel lavoro professionale per {activity}.",
        "educational_title": "Casi d'uso educativi di {name}",
        "educational_desc": "Usa {name} in contesti educativi per {activity}.",
        "personal_title": "Casi d'uso personali di {name}",
        "personal_desc": "Usa {name} nella vita personale per {activity}.",
    },
    "ru": {
        "professional_title": "Профессиональные сценарии использования {name}",
        "professional_desc": "Используйте {name} в профессиональной работе для {activity}.",
        "educational_title": "Образовательные сценарии использования {name}",
        "educational_desc": "Используйте {name} в образовательных сценариях для {activity}.",
        "personal_title": "Личные сценарии использования {name}",
        "personal_desc": "Используйте {name} в личной жизни для {activity}.",
    },
    "ar": {
        "professional_title": "حالات الاستخدام المهنية لـ {name}",
        "professional_desc": "استخدم {name} في العمل المهني لأجل {activity}.",
        "educational_title": "حالات الاستخدام التعليمية لـ {name}",
        "educational_desc": "استخدم {name} في البيئات التعليمية لأجل {activity}.",
        "personal_title": "حالات الاستخدام الشخصية لـ {name}",
        "personal_desc": "استخدم {name} في الحياة الشخصية لأجل {activity}.",
    },
    "nl": {
        "professional_title": "Professionele gebruikssituaties voor {name}",
        "professional_desc": "Gebruik {name} in professioneel werk voor {activity}.",
        "educational_title": "Educatieve gebruikssituaties voor {name}",
        "educational_desc": "Gebruik {name} in educatieve scenario's voor {activity}.",
        "personal_title": "Persoonlijke gebruikssituaties voor {name}",
        "personal_desc": "Gebruik {name} in het persoonlijke leven voor {activity}.",
    },
    "pl": {
        "professional_title": "Profesjonalne przypadki użycia programu {name}",
        "professional_desc": "Używaj programu {name} w pracy profesjonalnej do {activity}.",
        "educational_title": "Edukacyjne przypadki użycia programu {name}",
        "educational_desc": "Używaj programu {name} w scenariuszach edukacyjnych do {activity}.",
        "personal_title": "Osobiste przypadki użycia programu {name}",
        "personal_desc": "Używaj programu {name} w życiu osobistym do {activity}.",
    },
    "tr": {
        "professional_title": "{name} profesyonel kullanım senaryoları",
        "professional_desc": "Profesyonel işte {activity} için {name} kullanın.",
        "educational_title": "{name} eğitim kullanım senaryoları",
        "educational_desc": "Eğitim senaryolarında {activity} için {name} kullanın.",
        "personal_title": "{name} kişisel kullanım senaryoları",
        "personal_desc": "Kişisel yaşamda {activity} için {name} kullanın.",
    },
    "id": {
        "professional_title": "Kasus penggunaan profesional {name}",
        "professional_desc": "Gunakan {name} dalam pekerjaan profesional untuk {activity}.",
        "educational_title": "Kasus penggunaan edukatif {name}",
        "educational_desc": "Gunakan {name} dalam skenario edukatif untuk {activity}.",
        "personal_title": "Kasus penggunaan pribadi {name}",
        "personal_desc": "Gunakan {name} dalam kehidupan pribadi untuk {activity}.",
    },
    "vi": {
        "professional_title": "Tình huống sử dụng chuyên nghiệp của {name}",
        "professional_desc": "Sử dụng {name} trong công việc chuyên nghiệp để {activity}.",
        "educational_title": "Tình huống sử dụng giáo dục của {name}",
        "educational_desc": "Sử dụng {name} trong môi trường giáo dục để {activity}.",
        "personal_title": "Tình huống sử dụng cá nhân của {name}",
        "personal_desc": "Sử dụng {name} trong đời sống cá nhân để {activity}.",
    },
    "th": {
        "professional_title": "กรณีการใช้งานระดับมืออาชีพของ {name}",
        "professional_desc": "ใช้ {name} ในงานระดับมืออาชีพเพื่อ{activity}",
        "educational_title": "กรณีการใช้งานด้านการศึกษาของ {name}",
        "educational_desc": "ใช้ {name} ในสถานการณ์การศึกษาเพื่อ{activity}",
        "personal_title": "กรณีการใช้งานส่วนบุคคลของ {name}",
        "personal_desc": "ใช้ {name} ในชีวิตประจำวันเพื่อ{activity}",
    },
    "hi": {
        "professional_title": "{name} के पेशेवर उपयोग मामले",
        "professional_desc": "पेशेवर कार्य में {activity} के लिए {name} का उपयोग करें।",
        "educational_title": "{name} के शैक्षिक उपयोग मामले",
        "educational_desc": "शैक्षिक परिदृश्यों में {activity} के लिए {name} का उपयोग करें।",
        "personal_title": "{name} के व्यक्तिगत उपयोग मामले",
        "personal_desc": "व्यक्तिगत जीवन में {activity} के लिए {name} का उपयोग करें।",
    },
    "bn": {
        "professional_title": "{name} এর পেশাদার ব্যবহারের ক্ষেত্র",
        "professional_desc": "পেশাদার কাজে {activity}-এর জন্য {name} ব্যবহার করুন।",
        "educational_title": "{name} এর শিক্ষামূলক ব্যবহারের ক্ষেত্র",
        "educational_desc": "শিক্ষামূলক পরিস্থিতিতে {activity}-এর জন্য {name} ব্যবহার করুন।",
        "personal_title": "{name} এর ব্যক্তিগত ব্যবহারের ক্ষেত্র",
        "personal_desc": "ব্যক্তিগত জীবনে {activity}-এর জন্য {name} ব্যবহার করুন।",
    },
    "ms": {
        "professional_title": "Kes penggunaan profesional {name}",
        "professional_desc": "Gunakan {name} dalam kerja profesional untuk {activity}.",
        "educational_title": "Kes penggunaan pendidikan {name}",
        "educational_desc": "Gunakan {name} dalam senario pendidikan untuk {activity}.",
        "personal_title": "Kes penggunaan peribadi {name}",
        "personal_desc": "Gunakan {name} dalam kehidupan peribadi untuk {activity}.",
    },
    "uk": {
        "professional_title": "Професійні сценарії використання {name}",
        "professional_desc": "Використовуйте {name} у професійній роботі для {activity}.",
        "educational_title": "Освітні сценарії використання {name}",
        "educational_desc": "Використовуйте {name} в освітніх сценаріях для {activity}.",
        "personal_title": "Особисті сценарії використання {name}",
        "personal_desc": "Використовуйте {name} в особистому житті для {activity}.",
    },
}

# 各软件类别对应的使用场景内容（英文，作为源内容；industry/users 保持英文便于程序化处理）
# activity_localized 字段将填入 LANGUAGE_TEMPLATES 的 {activity} 占位符
CATEGORY_CONTENT = {
    "image-editing": {
        "industry": "Design & Photography",
        "professional": {
            "users": "Graphic designers, photographers, digital artists",
            "workflow": "Image retouching, compositing, digital painting, asset preparation for print/web",
            "benefits": "Industry-standard toolset for high-quality visual output and client deliverables",
            "activity_zh": "图像编辑、平面设计和数字艺术创作",
            "activity_ja": "画像編集、グラフィックデザイン、デジタルアート制作",
            "activity_ko": "이미지 편집, 그래픽 디자인, 디지털 아트 창작",
            "activity_es": "edición de imágenes, diseño gráfico y creación de arte digital",
            "activity_de": "Bildbearbeitung, Grafikdesign und digitale Kunst",
            "activity_fr": "édition d'images, conception graphique et création d'art numérique",
            "activity_pt": "edição de imagens, design gráfico e criação de arte digital",
            "activity_it": "editing di immagini, design grafico e creazione di arte digitale",
            "activity_ru": "редактирования изображений, графического дизайна и создания цифрового искусства",
            "activity_ar": "تحرير الصور والتصميم الجرافيكي وإنشاء الفن الرقمي",
            "activity_nl": "beeldbewerking, grafisch ontwerp en digitale kunst",
            "activity_pl": "edycji obrazów, projektowania graficznego i tworzenia cyfrowej sztuki",
            "activity_tr": "görüntü düzenleme, grafik tasarım ve dijital sanat oluşturma",
            "activity_id": "pengeditan gambar, desain grafis, dan pembuatan seni digital",
            "activity_vi": "chỉnh sửa hình ảnh, thiết kế đồ họa và tạo nghệ thuật số",
            "activity_th": "การแก้ไขภาพ การออกแบบกราฟิก และการสร้างศิลปะดิจิทัล",
            "activity_hi": "छवि संपादन, ग्राफ़िक डिज़ाइन और डिजिटल कला निर्माण",
            "activity_bn": "ইমেজ এডিটিং, গ্রাফিক ডিজাইন এবং ডিজিটাল আর্ট তৈরি",
            "activity_ms": "penyuntingan imej, reka bentuk grafik dan penciptaan seni digital",
            "activity_uk": "редагування зображень, графічного дизайну та створення цифрового мистецтва",
        },
        "educational": {
            "users": "Design students, educators, beginners",
            "workflow": "Learning image editing fundamentals, classroom demonstrations, assignments",
            "benefits": "Build foundational skills for design careers and creative projects",
            "activity_zh": "图像处理教学和学习",
            "activity_ja": "画像処理の教育と学習",
            "activity_ko": "이미지 처리 교육 및 학습",
            "activity_es": "enseñanza y aprendizaje del procesamiento de imágenes",
            "activity_de": "Bildverarbeitungsunterricht und -lernen",
            "activity_fr": "enseignement et apprentissage du traitement d'images",
            "activity_pt": "ensino e aprendizado de processamento de imagens",
            "activity_it": "insegnamento e apprendimento dell'elaborazione delle immagini",
            "activity_ru": "преподавания и изучения обработки изображений",
            "activity_ar": "تدريس وتعلم معالجة الصور",
            "activity_nl": "onderwijs en leren van beeldverwerking",
            "activity_pl": "nauczania i uczenia się przetwarzania obrazów",
            "activity_tr": "görüntü işleme eğitimi ve öğrenimi",
            "activity_id": "pengajaran dan pembelajaran pengolahan gambar",
            "activity_vi": "giảng dạy và học xử lý hình ảnh",
            "activity_th": "การสอนและการเรียนรู้การประมวลผลภาพ",
            "activity_hi": "छवि प्रसंस्करण शिक्षण और अधिगम",
            "activity_bn": "ইমেজ প্রসেসিং শিক্ষা ও শেখা",
            "activity_ms": "pengajaran dan pembelajaran pemprosesan imej",
            "activity_uk": "викладання та вивчення обробки зображень",
        },
        "personal": {
            "users": "Hobbyists, social media enthusiasts",
            "workflow": "Photo retouching, creative projects, social media content creation",
            "benefits": "Easy photo enhancement for personal memories and online sharing",
            "activity_zh": "个人照片编辑和社交媒体创作",
            "activity_ja": "個人の写真編集とSNSコンテンツ制作",
            "activity_ko": "개인 사진 편집 및 소셜 미디어 콘텐츠 제작",
            "activity_es": "edición de fotos personales y creación de contenido para redes sociales",
            "activity_de": "persönliche Fotobearbeitung und Social-Media-Inhaltserstellung",
            "activity_fr": "retouche photo personnelle et création de contenu pour les réseaux sociaux",
            "activity_pt": "edição de fotos pessoais e criação de conteúdo para redes sociais",
            "activity_it": "ritocco foto personale e creazione di contenuti per social media",
            "activity_ru": "личное редактирование фото и создание контента для соцсетей",
            "activity_ar": "تحرير الصور الشخصية وإنشاء محتوى لوسائل التواصل الاجتماعي",
            "activity_nl": "persoonlijke fotobewerking en sociale media-content creatie",
            "activity_pl": "osobista edycja zdjęć i tworzenie treści na media społecznościowe",
            "activity_tr": "kişisel fotoğraf düzenleme ve sosyal medya içeriği oluşturma",
            "activity_id": "pengeditan foto pribadi dan pembuatan konten media sosial",
            "activity_vi": "chỉnh sửa ảnh cá nhân và tạo nội dung mạng xã hội",
            "activity_th": "การแก้ไขภาพส่วนบุคคลและการสร้างเนื้อหาโซเชียลมีเดีย",
            "activity_hi": "व्यक्तिगत फ़ोटो संपादन और सोशल मीडिया सामग्री निर्माण",
            "activity_bn": "ব্যক্তিগত ছবি সম্পাদনা এবং সোশ্যাল মিডিয়া কন্টেন্ট তৈরি",
            "activity_ms": "penyuntingan foto peribadi dan penciptaan kandungan media sosial",
            "activity_uk": "особисте редагування фото та створення контенту для соцмереж",
        },
    },
    "design-collaboration": {
        "industry": "Design & Product",
        "professional": {
            "users": "UI/UX designers, product teams, design leads",
            "workflow": "Collaborative interface design, design system management, handoff to engineering",
            "benefits": "Real-time collaboration reduces review cycles and improves design-to-dev handoff",
            "activity_zh": "团队界面设计和协作",
            "activity_ja": "チームでのUIデザインとコラボレーション",
            "activity_ko": "팀 인터페이스 디자인 및 협업",
            "activity_es": "diseño de interfaces en equipo y colaboración",
            "activity_de": "kollaboratives Interface-Design und Teamarbeit",
            "activity_fr": "conception d'interface en équipe et collaboration",
            "activity_pt": "design de interface em equipe e colaboração",
            "activity_it": "design di interfaccia in team e collaborazione",
            "activity_ru": "командное проектирование интерфейсов и совместная работа",
            "activity_ar": "تصميم الواجهات الجماعي والتعاون",
            "activity_nl": "teaminterface-ontwerp en samenwerking",
            "activity_pl": "zespołowego projektowania interfejsów i współpracy",
            "activity_tr": "ekip arayüz tasarımı ve işbirliği",
            "activity_id": "desain antarmuka tim dan kolaborasi",
            "activity_vi": "thiết kế giao diện nhóm và cộng tác",
            "activity_th": "การออกแบบอินเทอร์เฟซเป็นทีมและการทำงานร่วมกัน",
            "activity_hi": "टीम इंटरफ़ेस डिज़ाइन और सहयोग",
            "activity_bn": "টিম ইন্টারফেস ডিজাইন এবং সহযোগিতা",
            "activity_ms": "reka bentuk antara muka pasukan dan kolaborasi",
            "activity_uk": "командне проектування інтерфейсів та співпраця",
        },
        "educational": {
            "users": "Design students, bootcamp participants, educators",
            "workflow": "Learning collaborative design, group projects, design critique sessions",
            "benefits": "Develop teamwork skills essential for modern product design careers",
            "activity_zh": "协作设计教学和团队项目",
            "activity_ja": "コラボレーションデザインの教育とチームプロジェクト",
            "activity_ko": "협업 디자인 교육 및 팀 프로젝트",
            "activity_es": "enseñanza de diseño colaborativo y proyectos en equipo",
            "activity_de": "kollaboratives Design-Lehren und Teamprojekte",
            "activity_fr": "enseignement du design collaboratif et projets d'équipe",
            "activity_pt": "ensino de design colaborativo e projetos em equipe",
            "activity_it": "insegnamento del design collaborativo e progetti di team",
            "activity_ru": "преподавание совместного дизайна и командные проекты",
            "activity_ar": "تدريس التصميم التعاوني والمشاريع الجماعية",
            "activity_nl": "collaboratief design-onderwijs en teamprojecten",
            "activity_pl": "nauczanie projektowania zespołowego i projekty grupowe",
            "activity_tr": "işbirlikçi tasarım eğitimi ve ekip projeleri",
            "activity_id": "pengajaran desain kolaboratif dan proyek tim",
            "activity_vi": "giảng dạy thiết kế cộng tác và dự án nhóm",
            "activity_th": "การสอนการออกแบบร่วมมือและโครงการกลุ่ม",
            "activity_hi": "सहयोगात्मक डिज़ाइन शिक्षण और टीम परियोजनाएं",
            "activity_bn": "সহযোগী ডিজাইন শিক্ষা এবং দলীয় প্রকল্প",
            "activity_ms": "pengajaran reka bentuk kolaboratif dan projek pasukan",
            "activity_uk": "викладання сумісного дизайну та командні проєкти",
        },
        "personal": {
            "users": "Freelance designers, side-project creators",
            "workflow": "Personal portfolio design, side project mockups, freelance client work",
            "benefits": "Free tier supports personal creative work and portfolio building",
            "activity_zh": "个人作品集和自由职业设计",
            "activity_ja": "個人のポートフォリオとフリーランスデザイン",
            "activity_ko": "개인 포트폴리오 및 프리랜서 디자인",
            "activity_es": "portafolio personal y diseño freelance",
            "activity_de": "persönliches Portfolio und Freelance-Design",
            "activity_fr": "portfolio personnel et design freelance",
            "activity_pt": "portfólio pessoal e design freelance",
            "activity_it": "portfolio personale e design freelance",
            "activity_ru": "личное портфолио и фриланс-дизайн",
            "activity_ar": "معرض شخصي وتصميم حر",
            "activity_nl": "persoonlijk portfolio en freelance design",
            "activity_pl": "osobiste portfolio i projektowanie freelancerskie",
            "activity_tr": "kişisel portföy ve serbest tasarım",
            "activity_id": "portofolio pribadi dan desain freelance",
            "activity_vi": "portfolio cá nhân và thiết kế freelance",
            "activity_th": "portfolio ส่วนบุคคลและการออกแบบฟรีแลนซ์",
            "activity_hi": "व्यक्तिगत पोर्टफोलियो और फ्रीलांस डिज़ाइन",
            "activity_bn": "ব্যক্তিগত পোর্টফোলিও এবং ফ্রিল্যান্স ডিজাইন",
            "activity_ms": "portfolio peribadi dan reka bentuk bebas",
            "activity_uk": "особисте портфоліо та фріланс-дизайн",
        },
    },
    "development-tools": {
        "industry": "Software Development",
        "professional": {
            "users": "Software engineers, devops teams, tech leads",
            "workflow": "Code editing, debugging, version control, CI/CD pipeline integration",
            "benefits": "Boosts developer productivity with intelligent tooling and integrations",
            "activity_zh": "代码编辑、调试和版本控制",
            "activity_ja": "コード編集、デバッグ、バージョン管理",
            "activity_ko": "코드 편집, 디버깅, 버전 관리",
            "activity_es": "edición de código, depuración y control de versiones",
            "activity_de": "Code-Bearbeitung, Debugging und Versionskontrolle",
            "activity_fr": "édition de code, débogage et contrôle de version",
            "activity_pt": "edição de código, depuração e controle de versão",
            "activity_it": "modifica del codice, debug e controllo versione",
            "activity_ru": "редактирование кода, отладку и контроль версий",
            "activity_ar": "تحرير الكود وتصحيحه والتحكم في الإصدارات",
            "activity_nl": "code-bewerking, debugging en versiebeheer",
            "activity_pl": "edycję kodu, debugowanie i kontrolę wersji",
            "activity_tr": "kod düzenleme, hata ayıklama ve sürüm kontrolü",
            "activity_id": "pengeditan kode, debugging, dan kontrol versi",
            "activity_vi": "chỉnh sửa mã, gỡ lỗi và kiểm soát phiên bản",
            "activity_th": "การแก้ไขโค้ด การดีบัก และการควบคุมเวอร์ชัน",
            "activity_hi": "कोड संपादन, डिबगिंग और संस्करण नियंत्रण",
            "activity_bn": "কোড সম্পাদনা, ডিবাগিং এবং ভার্সন কন্ট্রোল",
            "activity_ms": "penyuntingan kod, penyahpepijatan dan kawalan versi",
            "activity_uk": "редагування коду, зневадження та контроль версій",
        },
        "educational": {
            "users": "CS students, coding bootcamp learners, educators",
            "workflow": "Learning programming, completing assignments, building portfolio projects",
            "benefits": "Powerful learning environment with debugging and code completion",
            "activity_zh": "编程教学和代码学习",
            "activity_ja": "プログラミング教育とコード学習",
            "activity_ko": "프로그래밍 교육 및 코드 학습",
            "activity_es": "enseñanza de programación y aprendizaje de código",
            "activity_de": "Programmierunterricht und Code-Lernen",
            "activity_fr": "enseignement de la programmation et apprentissage du code",
            "activity_pt": "ensino de programação e aprendizado de código",
            "activity_it": "insegnamento della programmazione e apprendimento del codice",
            "activity_ru": "преподавание программирования и изучение кода",
            "activity_ar": "تدريس البرمجة وتعلم الكود",
            "activity_nl": "programmeeronderwijs en code leren",
            "activity_pl": "nauczanie programowania i nauka kodu",
            "activity_tr": "programlama eğitimi ve kod öğrenimi",
            "activity_id": "pengajaran pemrograman dan pembelajaran kode",
            "activity_vi": "giảng dạy lập trình và học mã",
            "activity_th": "การสอนการเขียนโปรแกรมและการเรียนรู้โค้ด",
            "activity_hi": "प्रोग्रामिंग शिक्षण और कोड अधिगम",
            "activity_bn": "প্রোগ্রামিং শিক্ষা এবং কোড শেখা",
            "activity_ms": "pengajaran pengaturcaraan dan pembelajaran kod",
            "activity_uk": "викладання програмування та вивчення коду",
        },
        "personal": {
            "users": "Hobbyist developers, open-source contributors",
            "workflow": "Personal projects, open-source contributions, side hustles",
            "benefits": "Free tier supports personal coding projects and skill development",
            "activity_zh": "个人编程项目和开源贡献",
            "activity_ja": "個人プログラミングプロジェクトとOSS貢献",
            "activity_ko": "개인 프로그래밍 프로젝트 및 오픈소스 기여",
            "activity_es": "proyectos de programación personal y contribuciones open-source",
            "activity_de": "persönliche Programmierprojekte und Open-Source-Beiträge",
            "activity_fr": "projets de programmation personnels et contributions open-source",
            "activity_pt": "projetos de programação pessoal e contribuições open-source",
            "activity_it": "progetti di programmazione personali e contributi open-source",
            "activity_ru": "личные программистские проекты и вклад в open-source",
            "activity_ar": "مشاريع البرمجة الشخصية ومساهمات المصدر المفتوح",
            "activity_nl": "persoonlijke programmeerprojecten en open-source bijdragen",
            "activity_pl": "osobiste projekty programistyczne i wkład w open-source",
            "activity_tr": "kişisel programlama projeleri ve açık kaynak katkıları",
            "activity_id": "proyek pemrograman pribadi dan kontribusi open-source",
            "activity_vi": "dự án lập trình cá nhân và đóng góp open-source",
            "activity_th": "โครงการเขียนโปรแกรมส่วนบุคคลและการมีส่วนร่วมใน open-source",
            "activity_hi": "व्यक्तिगत प्रोग्रामिंग परियोजनाएं और ओपन-सोर्स योगदान",
            "activity_bn": "ব্যক্তিগত প্রোগ্রামিং প্রকল্প এবং ওপেন-সোর্স অবদান",
            "activity_ms": "projek pengaturcaraan peribadi dan sumbangan sumber terbuka",
            "activity_uk": "особисті проєкти програмування та внесок у open-source",
        },
    },
    "media-player": {
        "industry": "Media & Entertainment",
        "professional": {
            "users": "Video editors, content producers, broadcasters",
            "workflow": "Media playback, preview, quality control, content review",
            "benefits": "Reliable playback for professional media production workflows",
            "activity_zh": "媒体播放和专业内容预览",
            "activity_ja": "メディア再生とプロフェッショナルコンテンツプレビュー",
            "activity_ko": "미디어 재생 및 전문 콘텐츠 미리보기",
            "activity_es": "reproducción de medios y vista previa de contenido profesional",
            "activity_de": "Medienwiedergabe und professionelle Inhaltsvorschau",
            "activity_fr": "lecture multimédia et aperçu de contenu professionnel",
            "activity_pt": "reprodução de mídia e pré-visualização de conteúdo profissional",
            "activity_it": "riproduzione multimediale e anteprima di contenuti professionali",
            "activity_ru": "воспроизведение медиа и предварительный просмотр профессионального контента",
            "activity_ar": "تشغيل الوسائط ومعاينة المحتوى المهني",
            "activity_nl": "mediaweergave en professionele contentvoorvertoning",
            "activity_pl": "odtwarzanie mediów i profesjonalny podgląd treści",
            "activity_tr": "medya oynatma ve profesyonel içerik önizleme",
            "activity_id": "pemutaran media dan pratinjau konten profesional",
            "activity_vi": "phát phương tiện và xem trước nội dung chuyên nghiệp",
            "activity_th": "การเล่นสื่อและการดูตัวอย่างเนื้อหาระดับมืออาชีพ",
            "activity_hi": "मीडिया प्लेबैक और पेशेवर सामग्री पूर्वावलोकन",
            "activity_bn": "মিডিয়া প্লেব্যাক এবং পেশাদার কন্টেন্ট প্রিভিউ",
            "activity_ms": "main semula media dan pratonton kandungan profesional",
            "activity_uk": "відтворення медіа та попередній перегляд професійного контенту",
        },
        "educational": {
            "users": "Students, educators, training content creators",
            "workflow": "Educational video playback, lecture recordings, training materials",
            "benefits": "Supports diverse media formats for educational content delivery",
            "activity_zh": "教学视频播放和讲座录制",
            "activity_ja": "教育動画の再生と講義録画",
            "activity_ko": "교육 동영상 재생 및 강의 녹화",
            "activity_es": "reproducción de videos educativos y grabación de clases",
            "activity_de": "Abspielen educativer Videos und Vorlesungsaufzeichnungen",
            "activity_fr": "lecture de vidéos éducatifs et enregistrement de cours",
            "activity_pt": "reprodução de vídeos educativos e gravação de aulas",
            "activity_it": "riproduzione di video educativi e registrazione di lezioni",
            "activity_ru": "воспроизведение обучающих видео и запись лекций",
            "activity_ar": "تشغيل مقاطع الفيديو التعليمية وتسجيل المحاضرات",
            "activity_nl": "afspelen van educatieve video's en college-opnames",
            "activity_pl": "odtwarzanie materiałów edukacyjnych i nagrywanie wykładów",
            "activity_tr": "eğitim videosu oynatma ve ders kaydı",
            "activity_id": "pemutaran video pendidikan dan rekaman kuliah",
            "activity_vi": "phát video giáo dục và ghi bài giảng",
            "activity_th": "การเล่นวิดีโอการศึกษาและการบันทึกการบรรยาย",
            "activity_hi": "शैक्षिक वीडियो प्लेबैक और व्याख्यान रिकॉर्डिंग",
            "activity_bn": "শিক্ষামূলক ভিডিও প্লেব্যাক এবং বক্তৃতা রেকর্ডিং",
            "activity_ms": "main semula video pendidikan dan rakaman kuliah",
            "activity_uk": "відтворення навчальних відео та запис лекцій",
        },
        "personal": {
            "users": "General consumers, movie enthusiasts",
            "workflow": "Personal media library, movie watching, music playback",
            "benefits": "Free high-quality media playback for personal entertainment",
            "activity_zh": "个人媒体库和影音娱乐",
            "activity_ja": "個人のメディアライブラリとエンターテインメント",
            "activity_ko": "개인 미디어 라이브러리 및 엔터테인먼트",
            "activity_es": "biblioteca de medios personal y entretenimiento",
            "activity_de": "persönliche Mediathek und Unterhaltung",
            "activity_fr": "médiathèque personnelle et divertissement",
            "activity_pt": "biblioteca de mídia pessoal e entretenimento",
            "activity_it": "libreria multimediale personale e intrattenimento",
            "activity_ru": "личная медиатека и развлечения",
            "activity_ar": "مكتبة الوسائط الشخصية والترفيه",
            "activity_nl": "persoonlijke mediabibliotheek en entertainment",
            "activity_pl": "osobista biblioteka mediów i rozrywka",
            "activity_tr": "kişisel medya kütüphanesi ve eğlence",
            "activity_id": "pustaka media pribadi dan hiburan",
            "activity_vi": "thư viện phương tiện cá nhân và giải trí",
            "activity_th": "ไลบรารีสื่อส่วนบุคคลและความบันเทิง",
            "activity_hi": "व्यक्तिगत मीडिया लाइब्रेरी और मनोरंजन",
            "activity_bn": "ব্যক্তিগত মিডিয়া লাইব্রেরি এবং বিনোদন",
            "activity_ms": "pustaka media peribadi dan hiburan",
            "activity_uk": "особиста медіатека та розваги",
        },
    },
    "note-taking": {
        "industry": "Knowledge Work",
        "professional": {
            "users": "Knowledge workers, project managers, researchers",
            "workflow": "Note organization, project documentation, knowledge bases",
            "benefits": "Centralizes knowledge and improves information retrieval",
            "activity_zh": "笔记整理和项目管理",
            "activity_ja": "ノート整理とプロジェクト管理",
            "activity_ko": "노트 정리 및 프로젝트 관리",
            "activity_es": "organización de notas y gestión de proyectos",
            "activity_de": "Notizorganisation und Projektmanagement",
            "activity_fr": "organisation de notes et gestion de projet",
            "activity_pt": "organização de notas e gestão de projetos",
            "activity_it": "organizzazione di note e gestione dei progetti",
            "activity_ru": "организацию заметок и управление проектами",
            "activity_ar": "تنظيم الملاحظات وإدارة المشاريع",
            "activity_nl": "notitieorganisatie en projectmanagement",
            "activity_pl": "organizację notatek i zarządzanie projektami",
            "activity_tr": "not organizasyonu ve proje yönetimi",
            "activity_id": "organisasi catatan dan manajemen proyek",
            "activity_vi": "tổ chức ghi chú và quản lý dự án",
            "activity_th": "การจัดระเบียบบันทึกและการจัดการโครงการ",
            "activity_hi": "नोट संगठन और परियोजना प्रबंधन",
            "activity_bn": "নোট সংগঠন এবং প্রকল্প ব্যবস্থাপনা",
            "activity_ms": "organisasi nota dan pengurusan projek",
            "activity_uk": "організацію нотаток та управління проєктами",
        },
        "educational": {
            "users": "Students, researchers, academics",
            "workflow": "Lecture notes, research organization, study materials",
            "benefits": "Improves learning outcomes with structured knowledge management",
            "activity_zh": "学习笔记和研究整理",
            "activity_ja": "学習ノートと研究整理",
            "activity_ko": "학습 노트 및 연구 정리",
            "activity_es": "notas de estudio y organización de investigación",
            "activity_de": "Lernnotizen und Forschungsorganisation",
            "activity_fr": "notes d'étude et organisation de la recherche",
            "activity_pt": "notas de estudo e organização de pesquisa",
            "activity_it": "note di studio e organizzazione della ricerca",
            "activity_ru": "учебные заметки и организацию исследований",
            "activity_ar": "ملاحظات الدراسة وتنظيم الأبحاث",
            "activity_nl": "studienotities en onderzoekorganisatie",
            "activity_pl": "notatki do nauki i organizację badań",
            "activity_tr": "çalışma notları ve araştırma organizasyonu",
            "activity_id": "catatan belajar dan organisasi penelitian",
            "activity_vi": "ghi chú học tập và tổ chức nghiên cứu",
            "activity_th": "บันทึกการเรียนและการจัดระเบียบการวิจัย",
            "activity_hi": "अध्ययन नोट्स और अनुसंधान संगठन",
            "activity_bn": "অধ্যয়ন নোট এবং গবেষণা সংগঠন",
            "activity_ms": "nota belajar dan organisasi penyelidikan",
            "activity_uk": "навчальні нотатки та організацію досліджень",
        },
        "personal": {
            "users": "Personal knowledge managers, journalers",
            "workflow": "Personal journaling, life organization, idea capture",
            "benefits": "Helps organize personal thoughts and life admin in one place",
            "activity_zh": "个人日记和生活记录",
            "activity_ja": "個人の日記と生活記録",
            "activity_ko": "개인 일기 및 생활 기록",
            "activity_es": "diario personal y registro de vida",
            "activity_de": "persönliches Tagebuch und Lebensaufzeichnungen",
            "activity_fr": "journal personnel et enregistrement de vie",
            "activity_pt": "diário pessoal e registro de vida",
            "activity_it": "diario personale e registrazione di vita",
            "activity_ru": "личный дневник и запись жизни",
            "activity_ar": "اليوميات الشخصية وتسجيل الحياة",
            "activity_nl": "persoonlijk dagboek en levensregistratie",
            "activity_pl": "osobisty dziennik i zapis życia",
            "activity_tr": "kişisel günlük ve yaşam kaydı",
            "activity_id": "jurnal pribadi dan pencatatan kehidupan",
            "activity_vi": "nhật ký cá nhân và ghi chép cuộc sống",
            "activity_th": "ไดอารี่ส่วนบุคคลและการบันทึกชีวิต",
            "activity_hi": "व्यक्तिगत डायरी और जीवन रिकॉर्डिंग",
            "activity_bn": "ব্যক্তিগত ডায়েরি এবং জীবন রেকর্ডিং",
            "activity_ms": "diari peribadi dan rekod kehidupan",
            "activity_uk": "особистий щоденник та запис життя",
        },
    },
    "office-suite": {
        "industry": "Business & Productivity",
        "professional": {
            "users": "Business professionals, analysts, administrators",
            "workflow": "Document creation, spreadsheet analysis, presentations",
            "benefits": "Standard productivity suite for business document workflows",
            "activity_zh": "办公文档和电子表格",
            "activity_ja": "オフィス文書とスプレッドシート",
            "activity_ko": "오피스 문서 및 스프레드시트",
            "activity_es": "documentos de oficina y hojas de cálculo",
            "activity_de": "Office-Dokumente und Tabellenkalkulation",
            "activity_fr": "documents bureautiques et feuilles de calcul",
            "activity_pt": "documentos de escritório e planilhas",
            "activity_it": "documenti d'ufficio e fogli di calcolo",
            "activity_ru": "офисные документы и электронные таблицы",
            "activity_ar": "مستندات المكتب وجداول البيانات",
            "activity_nl": "kantoordocumenten en spreadsheets",
            "activity_pl": "dokumenty biurowe i arkusze kalkulacyjne",
            "activity_tr": "ofis belgeleri ve elektronik tablolar",
            "activity_id": "dokumen kantor dan spreadsheet",
            "activity_vi": "tài liệu văn phòng và bảng tính",
            "activity_th": "เอกสารสำนักงานและสเปรดชีต",
            "activity_hi": "कार्यालय दस्तावेज़ और स्प्रेडशीट",
            "activity_bn": "অফিস নথি এবং স্প্রেডশিট",
            "activity_ms": "dokumen pejabat dan hamparan",
            "activity_uk": "офісні документи та електронні таблиці",
        },
        "educational": {
            "users": "Students, teachers, academic staff",
            "workflow": "Assignments, lesson plans, academic papers",
            "benefits": "Standard tools for academic document creation",
            "activity_zh": "学术论文和教学课件",
            "activity_ja": "学術論文と教育教材",
            "activity_ko": "학술 논문 및 교육 자료",
            "activity_es": "trabajos académicos y materiales educativos",
            "activity_de": "akademische Arbeiten und Bildungsmaterialien",
            "activity_fr": "travaux académiques et matériel éducatif",
            "activity_pt": "trabalhos acadêmicos e materiais educativos",
            "activity_it": "lavori accademici e materiali educativi",
            "activity_ru": "академические работы и учебные материалы",
            "activity_ar": "الأعمال الأكاديمية والمواد التعليمية",
            "activity_nl": "academische werken en educatief materiaal",
            "activity_pl": "prace akademickie i materiały edukacyjne",
            "activity_tr": "akademik çalışmalar ve eğitim materyalleri",
            "activity_id": "karya akademik dan materi pendidikan",
            "activity_vi": "công trình học thuật và tài liệu giáo dục",
            "activity_th": "งานวิชาการและวัสดุการศึกษา",
            "activity_hi": "शैक्षणिक कार्य और शैक्षिक सामग्री",
            "activity_bn": "একাডেমিক কাজ এবং শিক্ষা সামগ্রী",
            "activity_ms": "kerja akademik dan bahan pendidikan",
            "activity_uk": "академічні роботи та навчальні матеріали",
        },
        "personal": {
            "users": "Home users, personal finance managers",
            "workflow": "Personal budgets, household documents, invitations",
            "benefits": "Free alternatives for personal productivity tasks",
            "activity_zh": "个人理财和家庭文档",
            "activity_ja": "個人の家計管理と家庭文書",
            "activity_ko": "개인 재무 관리 및 가정 문서",
            "activity_es": "finanzas personales y documentos del hogar",
            "activity_de": "persönliche Finanzen und Haushaltsdokumente",
            "activity_fr": "finances personnelles et documents domestiques",
            "activity_pt": "finanças pessoais e documentos domésticos",
            "activity_it": "finanze personali e documenti domestici",
            "activity_ru": "личные финансы и домашние документы",
            "activity_ar": "الشؤون المالية الشخصية والوثائق المنزلية",
            "activity_nl": "persoonlijke financiën en huishouddocumenten",
            "activity_pl": "osobiste finanse i dokumenty domowe",
            "activity_tr": "kişisel finans ve ev belgeleri",
            "activity_id": "keuangan pribadi dan dokumen rumah tangga",
            "activity_vi": "tài chính cá nhân và tài liệu gia đình",
            "activity_th": "การเงินส่วนบุคคลและเอกสารครัวเรือน",
            "activity_hi": "व्यक्तिगत वित्त और घरेलू दस्तावेज़",
            "activity_bn": "ব্যক্তিগত অর্থ এবং গৃহস্থালী নথি",
            "activity_ms": "kewangan peribadi dan dokumen isi rumah",
            "activity_uk": "особисті фінанси та домашні документи",
        },
    },
    "security-software": {
        "industry": "Cybersecurity",
        "professional": {
            "users": "Security analysts, IT admins, compliance officers",
            "workflow": "Threat detection, vulnerability scanning, compliance auditing",
            "benefits": "Enterprise-grade security for protecting organizational assets",
            "activity_zh": "威胁检测和漏洞扫描",
            "activity_ja": "脅威検出と脆弱性スキャン",
            "activity_ko": "위협 탐지 및 취약점 스캔",
            "activity_es": "detección de amenazas y escaneo de vulnerabilidades",
            "activity_de": "Bedrohungserkennung und Schwachstellenscan",
            "activity_fr": "détection des menaces et analyse des vulnérabilités",
            "activity_pt": "detecção de ameaças e verificação de vulnerabilidades",
            "activity_it": "rilevamento delle minacce e scansione delle vulnerabilità",
            "activity_ru": "обнаружение угроз и сканирование уязвимостей",
            "activity_ar": "اكتشاف التهديدات وفحص الثغرات",
            "activity_nl": "bedreigingsdetectie en kwetsbaarheidsscans",
            "activity_pl": "wykrywanie zagrożeń i skanowanie podatności",
            "activity_tr": "tehdit tespiti ve güvenlik açığı taraması",
            "activity_id": "deteksi ancaman dan pemindaian kerentanan",
            "activity_vi": "phát hiện mối đe dọa và quét lỗ hổng",
            "activity_th": "การตรวจจับภัยคุกคามและการสแกนช่องโหว่",
            "activity_hi": "खतरा पहचान और कमजोरी स्कैनिंग",
            "activity_bn": "হুমকি সনাক্তকরণ এবং দুর্বলতা স্ক্যান",
            "activity_ms": "pengesanan ancaman dan imbasan kerentanan",
            "activity_uk": "виявлення загроз та сканування вразливостей",
        },
        "educational": {
            "users": "Cybersecurity students, security trainees",
            "workflow": "Security training, lab exercises, certification prep",
            "benefits": "Hands-on practice with industry-standard security tools",
            "activity_zh": "安全培训和实验练习",
            "activity_ja": "セキュリティ教育と演習",
            "activity_ko": "보안 교육 및 실습",
            "activity_es": "formación en seguridad y ejercicios prácticos",
            "activity_de": "Sicherheitsschulung und Laborübungen",
            "activity_fr": "formation en sécurité et exercices pratiques",
            "activity_pt": "treinamento de segurança e exercícios práticos",
            "activity_it": "formazione sulla sicurezza ed esercizi pratici",
            "activity_ru": "обучение безопасности и практические занятия",
            "activity_ar": "تدريب الأمن وتمارين المختبر",
            "activity_nl": "beveiligingstraining en laboefeningen",
            "activity_pl": "szkolenie z bezpieczeństwa i ćwiczenia laboratoryjne",
            "activity_tr": "güvenlik eğitimi ve laboratuvar alıştırmaları",
            "activity_id": "pelatihan keamanan dan latihan lab",
            "activity_vi": "đào tạo bảo mật và bài tập thực hành",
            "activity_th": "การฝึกอบรมด้านความปลอดภัยและแบบฝึกหัดในห้องแล็บ",
            "activity_hi": "सुरक्षा प्रशिक्षण और लैब अभ्यास",
            "activity_bn": "নিরাপত্তা প্রশিক্ষণ এবং ল্যাব অনুশীলন",
            "activity_ms": "latihan keselamatan dan latihan makmal",
            "activity_uk": "навчання з безпеки та лабораторні вправи",
        },
        "personal": {
            "users": "Home users, privacy-conscious individuals",
            "workflow": "Personal device protection, privacy tools, secure browsing",
            "benefits": "Protects personal data and online privacy",
            "activity_zh": "个人设备保护和隐私安全",
            "activity_ja": "個人のデバイス保護とプライバシー保護",
            "activity_ko": "개인 기기 보호 및 프라이버시 보안",
            "activity_es": "protección de dispositivos personales y seguridad de privacidad",
            "activity_de": "persönlichen Geräteschutz und Datensicherheit",
            "activity_fr": "protection des appareils personnels et sécurité de la vie privée",
            "activity_pt": "proteção de dispositivos pessoais e segurança de privacidade",
            "activity_it": "protezione dei dispositivi personali e sicurezza della privacy",
            "activity_ru": "защиту личных устройств и конфиденциальность",
            "activity_ar": "حماية الأجهزة الشخصية وأمان الخصوصية",
            "activity_nl": "persoonlijke apparaatbescherming en privacybeveiliging",
            "activity_pl": "ochronę urządzeń osobistych i bezpieczeństwo prywatności",
            "activity_tr": "kişisel cihaz koruma ve gizlilik güvenliği",
            "activity_id": "perlindungan perangkat pribadi dan keamanan privasi",
            "activity_vi": "bảo vệ thiết bị cá nhân và bảo mật quyền riêng tư",
            "activity_th": "การป้องกันอุปกรณ์ส่วนบุคคลและความปลอดภัยของความเป็นส่วนตัว",
            "activity_hi": "व्यक्तिगत डिवाइस सुरक्षा और गोपनीयता सुरक्षा",
            "activity_bn": "ব্যক্তিগত ডিভাইস সুরক্ষা এবং গোপনীয়তা নিরাপত্তা",
            "activity_ms": "perlindungan peranti peribadi dan keselamatan privasi",
            "activity_uk": "захист особистих пристроїв та безпеку конфіденційності",
        },
    },
    "system-utilities": {
        "industry": "IT Operations",
        "professional": {
            "users": "System admins, IT operations, DevOps engineers",
            "workflow": "System monitoring, file management, automation scripts",
            "benefits": "Streamlines system administration and operational efficiency",
            "activity_zh": "系统监控和文件管理",
            "activity_ja": "システム監視とファイル管理",
            "activity_ko": "시스템 모니터링 및 파일 관리",
            "activity_es": "monitoreo del sistema y gestión de archivos",
            "activity_de": "Systemüberwachung und Dateiverwaltung",
            "activity_fr": "surveillance du système et gestion des fichiers",
            "activity_pt": "monitoramento do sistema e gestão de arquivos",
            "activity_it": "monitoraggio del sistema e gestione dei file",
            "activity_ru": "мониторинг системы и управление файлами",
            "activity_ar": "مراقبة النظام وإدارة الملفات",
            "activity_nl": "systeemmonitoring en bestandsbeheer",
            "activity_pl": "monitorowanie systemu i zarządzanie plikami",
            "activity_tr": "sistem izleme ve dosya yönetimi",
            "activity_id": "pemantauan sistem dan manajemen file",
            "activity_vi": "giám sát hệ thống và quản lý tệp",
            "activity_th": "การตรวจสอบระบบและการจัดการไฟล์",
            "activity_hi": "सिस्टम निगरानी और फ़ाइल प्रबंधन",
            "activity_bn": "সিস্টেম মনিটরিং এবং ফাইল ব্যবস্থাপনা",
            "activity_ms": "pemantauan sistem dan pengurusan fail",
            "activity_uk": "моніторинг системи та управління файлами",
        },
        "educational": {
            "users": "IT students, sysadmin trainees",
            "workflow": "Learning system administration, lab environments",
            "benefits": "Practical experience with industry-standard utilities",
            "activity_zh": "系统管理教学和实验",
            "activity_ja": "システム管理教育と演習",
            "activity_ko": "시스템 관리 교육 및 실습",
            "activity_es": "enseñanza de administración de sistemas y laboratorios",
            "activity_de": "Systemverwaltungsunterricht und Labore",
            "activity_fr": "enseignement de l'administration système et travaux pratiques",
            "activity_pt": "ensino de administração de sistemas e laboratórios",
            "activity_it": "insegnamento dell'amministrazione di sistema e laboratori",
            "activity_ru": "преподавание системного администрирования и лабораторные",
            "activity_ar": "تدريس إدارة النظام والمختبرات",
            "activity_nl": "systeembeheeronderwijs en labs",
            "activity_pl": "nauczanie administracji systemem i laboratoria",
            "activity_tr": "sistem yönetimi eğitimi ve laboratuvarlar",
            "activity_id": "pengajaran administrasi sistem dan lab",
            "activity_vi": "giảng dạy quản trị hệ thống và phòng lab",
            "activity_th": "การสอนการดูแลระบบและห้องแล็บ",
            "activity_hi": "सिस्टम प्रशासन शिक्षण और लैब",
            "activity_bn": "সিস্টেম প্রশাসন শিক্ষা এবং ল্যাব",
            "activity_ms": "pengajaran pentadbiran sistem dan makmal",
            "activity_uk": "викладання системного адміністрування та лабораторні",
        },
        "personal": {
            "users": "Power users, home lab enthusiasts",
            "workflow": "Personal computer maintenance, file organization, system tweaks",
            "benefits": "Free utilities for keeping personal systems running smoothly",
            "activity_zh": "个人电脑维护和文件整理",
            "activity_ja": "個人のPCメンテナンスとファイル整理",
            "activity_ko": "개인 PC 유지보수 및 파일 정리",
            "activity_es": "mantenimiento de la computadora personal y organización de archivos",
            "activity_de": "PC-Wartung und Dateiorganisation",
            "activity_fr": "maintenance de l'ordinateur personnel et organisation des fichiers",
            "activity_pt": "manutenção do computador pessoal e organização de arquivos",
            "activity_it": "manutenzione del computer personale e organizzazione dei file",
            "activity_ru": "обслуживание личного компьютера и организацию файлов",
            "activity_ar": "صيانة الكمبيوتر الشخصي وتنظيم الملفات",
            "activity_nl": "persoonlijk computeronderhoud en bestandsorganisatie",
            "activity_pl": "konserwacja komputera osobistego i organizacja plików",
            "activity_tr": "kişisel bilgisayar bakımı ve dosya organizasyonu",
            "activity_id": "pemeliharaan komputer pribadi dan organisasi file",
            "activity_vi": "bảo trì máy tính cá nhân và tổ chức tệp",
            "activity_th": "การบำรุงรักษาคอมพิวเตอร์ส่วนบุคคลและการจัดระเบียบไฟล์",
            "activity_hi": "व्यक्तिगत कंप्यूटर रखरखाव और फ़ाइल संगठन",
            "activity_bn": "ব্যক্তিগত কম্পিউটার রক্ষণাবেক্ষণ এবং ফাইল সংগঠন",
            "activity_ms": "penyelenggaraan komputer peribadi dan organisasi fail",
            "activity_uk": "обслуговування персонального комп'ютера та організацію файлів",
        },
    },
    "team-communication": {
        "industry": "Business Communication",
        "professional": {
            "users": "Distributed teams, project managers, executives",
            "workflow": "Channel-based messaging, video calls, file sharing, integrations",
            "benefits": "Reduces email overload and accelerates team decision-making",
            "activity_zh": "团队沟通和项目管理",
            "activity_ja": "チームコミュニケーションとプロジェクト管理",
            "activity_ko": "팀 커뮤니케이션 및 프로젝트 관리",
            "activity_es": "comunicación de equipo y gestión de proyectos",
            "activity_de": "Teamkommunikation und Projektmanagement",
            "activity_fr": "communication d'équipe et gestion de projet",
            "activity_pt": "comunicação de equipe e gestão de projetos",
            "activity_it": "comunicazione di team e gestione dei progetti",
            "activity_ru": "командное общение и управление проектами",
            "activity_ar": "تواصل الفريق وإدارة المشاريع",
            "activity_nl": "teamcommunicatie en projectmanagement",
            "activity_pl": "komunikację zespołu i zarządzanie projektami",
            "activity_tr": "ekip iletişimi ve proje yönetimi",
            "activity_id": "komunikasi tim dan manajemen proyek",
            "activity_vi": "giao tiếp nhóm và quản lý dự án",
            "activity_th": "การสื่อสารในทีมและการจัดการโครงการ",
            "activity_hi": "टीम संचार और परियोजना प्रबंधन",
            "activity_bn": "টিম যোগাযোগ এবং প্রকল্প ব্যবস্থাপনা",
            "activity_ms": "komunikasi pasukan dan pengurusan projek",
            "activity_uk": "комунікацію команди та управління проєктами",
        },
        "educational": {
            "users": "Student teams, online course groups, educators",
            "workflow": "Group project coordination, study groups, class announcements",
            "benefits": "Facilitates collaborative learning and group work coordination",
            "activity_zh": "学习小组和课程协作",
            "activity_ja": "学習グループとコースコラボレーション",
            "activity_ko": "학습 그룹 및 코스 협업",
            "activity_es": "grupos de estudio y colaboración en cursos",
            "activity_de": "Lerngruppen und Kurszusammenarbeit",
            "activity_fr": "groupes d'étude et collaboration de cours",
            "activity_pt": "grupos de estudo e colaboração em cursos",
            "activity_it": "gruppi di studio e collaborazione nei corsi",
            "activity_ru": "учебные группы и сотрудничество на курсах",
            "activity_ar": "مجموعات الدراسة والتعاون في الدورات",
            "activity_nl": "studiegroepen en cursussamenwerking",
            "activity_pl": "grupy studyjne i współpraca na kursach",
            "activity_tr": "çalışma grupları ve kurs işbirliği",
            "activity_id": "kelompok belajar dan kolaborasi kursus",
            "activity_vi": "nhóm học tập và cộng tác khóa học",
            "activity_th": "กลุ่มศึกษาและการทำงานร่วมกันในหลักสูตร",
            "activity_hi": "अध्ययन समूह और पाठ्यक्रम सहयोग",
            "activity_bn": "অধ্যয়ন দল এবং কোর্স সহযোগিতা",
            "activity_ms": "kumpulan belajar dan kolaborasi kursus",
            "activity_uk": "навчальні групи та співпраця на курсах",
        },
        "personal": {
            "users": "Friend groups, family chats, community organizers",
            "workflow": "Group chats, event planning, community coordination",
            "benefits": "Free tier supports personal group communication needs",
            "activity_zh": "朋友群聊和社区活动",
            "activity_ja": "友人チャットとコミュニティ活動",
            "activity_ko": "친구 그룹 채팅 및 커뮤니티 활동",
            "activity_es": "chats de amigos y actividades comunitarias",
            "activity_de": "Freundes-Chats und Community-Aktivitäten",
            "activity_fr": "discussions entre amis et activités communautaires",
            "activity_pt": "chats de amigos e atividades comunitárias",
            "activity_it": "chat tra amici e attività comunitarie",
            "activity_ru": "дружеские чаты и общественные мероприятия",
            "activity_ar": "دردشات الأصدقاء والأنشطة المجتمعية",
            "activity_nl": "vrienden-chats en gemeenschapsactiviteiten",
            "activity_pl": "czaty ze znajomymi i działania społeczne",
            "activity_tr": "arkadaş sohbetleri ve topluluk etkinlikleri",
            "activity_id": "obrolan teman dan aktivitas komunitas",
            "activity_vi": "trò chuyện bạn bè và hoạt động cộng đồng",
            "activity_th": "แชทเพื่อนและกิจกรรมชุมชน",
            "activity_hi": "मित्र चैट और सामुदायिक गतिविधियां",
            "activity_bn": "বন্ধু চ্যাট এবং কমিউনিটি কার্যকলাপ",
            "activity_ms": "sembang rakan dan aktiviti komuniti",
            "activity_uk": "дружні чати та громадські заходи",
        },
    },
    "video-conferencing": {
        "industry": "Communication & Collaboration",
        "professional": {
            "users": "Remote teams, sales reps, consultants",
            "workflow": "Video meetings, webinars, screen sharing, recording",
            "benefits": "Enables remote work and global client communication",
            "activity_zh": "视频会议和网络研讨会",
            "activity_ja": "ビデオ会議とウェビナー",
            "activity_ko": "화상 회의 및 웨비나",
            "activity_es": "videoconferencias y seminarios web",
            "activity_de": "Videokonferenzen und Webinare",
            "activity_fr": "vidéoconférences et webinaires",
            "activity_pt": "videoconferências e webinars",
            "activity_it": "videoconferenze e webinar",
            "activity_ru": "видеоконференции и вебинары",
            "activity_ar": "مؤتمرات الفيديو والندوات الإلكترونية",
            "activity_nl": "videoconferenties en webinars",
            "activity_pl": "wideokonferencje i webinary",
            "activity_tr": "görüntülü konferanslar ve web seminerleri",
            "activity_id": "konferensi video dan webinar",
            "activity_vi": "hội nghị video và hội thảo web",
            "activity_th": "การประชุมทางวิดีโอและสัมมนาทางเว็บ",
            "activity_hi": "वीडियो सम्मेलन और वेबिनार",
            "activity_bn": "ভিডিও কনফারেন্স এবং ওয়েবিনার",
            "activity_ms": "persidangan video dan webinar",
            "activity_uk": "відеоконференції та вебінари",
        },
        "educational": {
            "users": "Online students, remote educators, trainers",
            "workflow": "Online classes, virtual office hours, remote tutoring",
            "benefits": "Enables remote learning and global education access",
            "activity_zh": "在线课程和远程教学",
            "activity_ja": "オンライン授業とリモート教育",
            "activity_ko": "온라인 수업 및 원격 교육",
            "activity_es": "clases en línea y educación a distancia",
            "activity_de": "Online-Unterricht und Fernbildung",
            "activity_fr": "cours en ligne et enseignement à distance",
            "activity_pt": "aulas online e educação a distância",
            "activity_it": "lezioni online e istruzione a distanza",
            "activity_ru": "онлайн-уроки и дистанционное обучение",
            "activity_ar": "الفصول عبر الإنترنت والتعليم عن بعد",
            "activity_nl": "onlinelessen en afstandsonderwijs",
            "activity_pl": "lekcje online i kształcenie na odległość",
            "activity_tr": "çevrimiçi dersler ve uzaktan eğitim",
            "activity_id": "kelas online dan pendidikan jarak jauh",
            "activity_vi": "lớp học trực tuyến và giáo dục từ xa",
            "activity_th": "ชั้นเรียนออนไลน์และการศึกษาทางไกล",
            "activity_hi": "ऑनलाइन कक्षाएं और दूरस्थ शिक्षा",
            "activity_bn": "অনলাইন ক্লাস এবং দূরবর্তী শিক্ষা",
            "activity_ms": "kelas dalam talian dan pendidikan jarak jauh",
            "activity_uk": "онлайн-уроки та дистанційне навчання",
        },
        "personal": {
            "users": "Families, friends, community groups",
            "workflow": "Family video calls, friend catch-ups, virtual events",
            "benefits": "Free video calls keep personal connections strong across distances",
            "activity_zh": "家庭视频通话和朋友聚会",
            "activity_ja": "家族とのビデオ通話や友人との交流",
            "activity_ko": "가족 화상 통화 및 친구 모임",
            "activity_es": "videollamadas familiares y reuniones de amigos",
            "activity_de": "Familien-Videoanrufe und Freundetreffen",
            "activity_fr": "appels vidéo familiaux et retrouvailles entre amis",
            "activity_pt": "videochamadas familiares e encontros de amigos",
            "activity_it": "videochiamate familiari e incontri tra amici",
            "activity_ru": "семейные видеозвонки и встречи с друзьями",
            "activity_ar": "مكالمات الفيديو العائلية ولقاءات الأصدقاء",
            "activity_nl": "familie-video-oproepen en vriendenontmoetingen",
            "activity_pl": "rodzinne rozmowy wideo i spotkania ze znajomymi",
            "activity_tr": "aile görüntülü aramaları ve arkadaş buluşmaları",
            "activity_id": "panggilan video keluarga dan pertemuan teman",
            "activity_vi": "cuộc gọi video gia đình và gặp gỡ bạn bè",
            "activity_th": "การโทรวิดีโอครอบครัวและการพบปะเพื่อน",
            "activity_hi": "पारिवारिक वीडियो कॉल और दोस्तों से मुलाकात",
            "activity_bn": "পারিবারিক ভিডিও কল এবং বন্ধু দেখা",
            "activity_ms": "panggilan video keluarga dan perjumpaan rakan",
            "activity_uk": "сімейні відеодзвінки та зустрічі з друзями",
        },
    },
}

# 默认类别（用于未知类别回退）
DEFAULT_CATEGORY_CONTENT = {
    "industry": "General",
    "professional": {
        "users": "Professional users",
        "workflow": "Daily professional tasks and workflows",
        "benefits": "Improves productivity and workflow efficiency",
    },
    "educational": {
        "users": "Students and educators",
        "workflow": "Learning and teaching activities",
        "benefits": "Supports educational activities and skill development",
    },
    "personal": {
        "users": "Personal users",
        "workflow": "Personal projects and everyday tasks",
        "benefits": "Free tier supports personal productivity needs",
    },
}

# 默认 activity（用于未知类别回退）
DEFAULT_ACTIVITY = {
    "zh": "日常工作任务", "ja": "日常業務タスク", "ko": "일상 업무 작업",
    "es": "tareas laborales diarias", "de": "tägliche Arbeitsaufgaben",
    "fr": "tâches professionnelles quotidiennes", "pt": "tarefas diárias de trabalho",
    "it": "attività lavorative quotidiane", "ru": "повседневные рабочие задачи",
    "ar": "المهام العملية اليومية", "nl": "dagelijkse werkzaamheden",
    "pl": "codzienne zadania zawodowe", "tr": "günlük iş görevleri",
    "id": "tugas harian", "vi": "nhiệm vụ hàng ngày",
    "th": "งานประจำวัน", "hi": "दैनिक कार्य कार्य",
    "bn": "দৈনিক কাজ", "ms": "tugas harian", "uk": "повсякденні робочі завдання",
}


def load_proprietary_catalog(data_dir: Path) -> List[Dict[str, Any]]:
    """加载商业软件目录。"""
    catalog_path = data_dir / "proprietary_catalog.json"
    if not catalog_path.exists():
        print(f"❌ catalog 不存在: {catalog_path}")
        return []
    with catalog_path.open("r", encoding="utf-8") as f:
        return json.load(f)


def build_use_case_record(
    software: Dict[str, Any],
    scenario: str,
    lang: str,
) -> Dict[str, Any]:
    """构建单条使用场景记录。"""
    sid = software["id"]
    sname = software.get("name", sid)
    category = software.get("category", "unknown")
    today = datetime.now(timezone.utc).strftime("%Y-%m-%d")

    cat_data = CATEGORY_CONTENT.get(category, DEFAULT_CATEGORY_CONTENT)
    scenario_data = cat_data.get(scenario, DEFAULT_CATEGORY_CONTENT.get(scenario, {}))
    templates = LANGUAGE_TEMPLATES.get(lang, LANGUAGE_TEMPLATES["zh"])

    # 获取当前语言对应的 activity 文本
    activity_key = f"activity_{lang}"
    activity = scenario_data.get(activity_key) if isinstance(scenario_data, dict) else None
    if not activity:
        activity = DEFAULT_ACTIVITY.get(lang, DEFAULT_ACTIVITY["zh"])

    title = templates[f"{scenario}_title"].format(name=sname)
    description = templates[f"{scenario}_desc"].format(name=sname, activity=activity)

    use_case_details = {
        "industry": cat_data.get("industry", "General"),
        "users": scenario_data.get("users", ""),
        "workflow": scenario_data.get("workflow", ""),
        "benefits": scenario_data.get("benefits", ""),
    }

    return {
        "id": f"{sid}-{scenario}-{lang}",
        "softwareId": sid,
        "scenario": scenario,
        "lang": lang,
        "title": title,
        "description": description,
        "useCaseDetails": use_case_details,
        "reviewStatus": "pending",
        "aiGenerated": True,
        "metadata": {
            "created": today,
            "sourceLang": "en",
        },
        "_meta": {
            "source": "ai-generated-mock",
            "schema_version": SCHEMA_VERSION,
            "unverified_fields": ["description", "useCaseDetails"],
            "confidence": "medium",
        },
    }


def write_one_use_case(
    out_dir: Path,
    software: Dict[str, Any],
    scenario: str,
    lang: str,
) -> Dict[str, Any]:
    """生成并写入单条使用场景数据，返回记录。"""
    record = build_use_case_record(software, scenario, lang)
    out_path = out_dir / f"{software['id']}-{scenario}-{lang}.json"
    with out_path.open("w", encoding="utf-8") as f:
        json.dump(record, f, ensure_ascii=False, indent=2)
    return record


def run_generate_use_cases(data_dir: Path) -> List[Dict[str, Any]]:
    """生成所有使用场景数据（500×3×20=30,000条）。"""
    print("=" * 70)
    print("📋 OSSAF Pipeline - Step 6: 生成使用场景数据")
    print("=" * 70)

    catalog = load_proprietary_catalog(data_dir)
    if not catalog:
        print("❌ proprietary_catalog.json 为空，请先运行 collect_proprietary")
        return []

    out_dir = data_dir / "use_cases"
    out_dir.mkdir(parents=True, exist_ok=True)

    total = len(catalog) * len(SCENARIOS) * len(LANGUAGES)
    print(f"  软件数: {len(catalog)} | 场景数: {len(SCENARIOS)} | 语言数: {len(LANGUAGES)}")
    print(f"  预期产出: {total} 条使用场景数据")

    t0 = time.time()
    results: List[Dict[str, Any]] = []

    # 构造所有任务
    tasks = [
        (out_dir, sw, scenario, lang)
        for sw in catalog
        for scenario in SCENARIOS
        for lang in LANGUAGES
    ]

    # 并发写入
    with ThreadPoolExecutor(max_workers=20) as executor:
        futures = [
            executor.submit(write_one_use_case, *task) for task in tasks
        ]
        for fut in tqdm(
            as_completed(futures),
            total=len(futures),
            desc="生成使用场景",
            unit="条",
        ):
            results.append(fut.result())

    elapsed = time.time() - t0
    print(f"\n  ⏱️  耗时: {elapsed:.2f}s")
    print(f"  📊 生成结果: {len(results)}/{total} 条")
    print(f"  📁 输出目录: {out_dir}")
    return results


def main():
    parser = argparse.ArgumentParser(description="OSSAF Pipeline - 生成使用场景数据")
    parser.add_argument("--data-dir", default="data", help="数据目录")
    args = parser.parse_args()

    data_dir = Path(args.data_dir)
    if not data_dir.exists():
        print(f"❌ 数据目录不存在: {data_dir}")
        sys.exit(1)

    results = run_generate_use_cases(data_dir)
    print(f"\n✅ 使用场景数据生成完成: {len(results)} 条")


if __name__ == "__main__":
    main()
